/**
 * Prose propre au montant et à l'État, pour les pages /:state/:amount-after-taxes.
 *
 * Le contrôle d'unicité a trouvé 3 259 paires de pages proches à 100 % : les
 * cent vingt pages d'État partageaient le même texte, seuls les nombres
 * changeaient, et un contrôle qui normalise les nombres voit alors deux pages
 * identiques. Un moteur aussi.
 *
 * Plutôt que d'écrire cent vingt textes, on en écrit vingt-deux : un par
 * montant et un par État. Chaque page porte la paire qui lui correspond, et
 * aucune combinaison ne se répète. Les paragraphes disent quelque chose que la
 * page ne dit pas ailleurs : à quoi ressemble ce niveau de salaire dans la vie
 * réelle, et ce qui distingue cet État des autres une fois l'impôt payé.
 */

/** Ce que représente ce niveau de salaire, indépendamment de l'État. */
export const PROSE_MONTANT: Record<number, string> = {
  30000:
    "A salary of $30,000 sits close to the full-time federal minimum wage in real terms and well below the national median household income. It is typical of retail, food service, care work and entry-level administrative roles, and it usually assumes a second earner, a roommate or subsidised housing to work as a household budget. At this level the federal tax bill is modest: after the standard deduction, most of the income falls in the 10 and 12 per cent brackets, and FICA at 7.65 per cent takes more than income tax does. The Earned Income Tax Credit and the Saver's Credit both matter here and are routinely missed. Two habits matter more than any deduction at this level: capturing an employer match if one exists, however small, and filing a return even in a year with no tax owed, because the refundable credits are only paid to those who file.",
  40000:
    "A $40,000 salary is common for skilled trades apprentices, teaching assistants, junior clerical staff and experienced retail supervisors. It is enough to run a one-person household in most of the country and tight in any coastal metro. Federal tax stays largely in the 12 per cent bracket after the standard deduction, so the marginal effect of a raise is mild, and FICA remains the larger deduction. This is the income band where a workplace retirement match is most often left on the table: contributing enough to capture it is the single highest-return decision available at this salary. The practical question at $40,000 is rarely which bracket applies but how much of the gross survives housing: at the conventional thirty per cent ceiling, that is around $1,000 a month, which buys very different things in Ohio and in California.",
  50000:
    "At $50,000, a worker is near the median for an individual American earner, though still below the median household, which counts two incomes in most cases. The salary covers teachers in many states, administrative professionals, technicians and skilled trades early in a career. Federally, part of the income now reaches the 22 per cent bracket, which makes pre-tax contributions worth measurably more than they were at $40,000: every dollar into a traditional 401(k) saves 22 cents rather than 12. It is also the level at which the choice between a high-tax and a no-income-tax state starts to show up in real money. It is also the salary at which a Roth contribution usually beats a traditional one, because the tax saved today is modest and the decades of tax-free growth ahead are long.",
  60000:
    "A $60,000 salary supports a comfortable single-person household almost anywhere outside the most expensive metros, and a modest family budget in low-cost regions. It is typical of experienced tradespeople, nurses early in a career, mid-level administrators and many engineering graduates in their first years. The marginal federal rate is 22 per cent for a single filer, so a $5,000 pre-tax contribution saves $1,100 federally before any state saving. At this level the difference between the states is roughly $2,000 to $3,000 a year between the lightest and the heaviest, which is real but rarely decisive on its own. A useful check at this level is the savings rate rather than the balance: fifteen per cent of gross, including any employer match, is what most retirement projections assume, and it is achievable here in most of the country.",
  70000:
    "At $70,000 a single filer is comfortably above the median individual income and within reach of the financial habits that compound: a full emergency fund, a maxed IRA, a meaningful 401(k) contribution. The salary is typical of experienced nurses, software developers outside the major hubs, project managers and skilled specialists. The marginal federal rate remains 22 per cent, which means the top slice of income is taxed at more than twice the rate of the bottom slice, and it is the slice that pre-tax contributions remove first. Housing is usually still the constraint rather than tax. At this salary the marginal value of a raise starts to depend on where you live as much as on the raise itself: the same $5,000 is worth about $3,600 after federal tax in a no-income-tax state and closer to $3,200 in a high-tax one.",
  75000:
    "A $75,000 salary is often quoted as the point at which additional income stops improving day-to-day wellbeing much, a finding from research that has since been qualified but still marks a recognisable threshold. In practice it supports a single-earner household in most of the country and a two-earner family comfortably. Federally, the marginal rate is 22 per cent and the effective rate lands near 12 to 14 per cent after the standard deduction. This is also the level at which the phase-outs begin to matter: several credits and deduction allowances start to taper in the seventies and eighties. Anyone near this level with access to a high-deductible health plan should look hard at the HSA, the only account that escapes income tax on the way in, on growth and on qualified spending.",
  80000:
    "At $80,000, a single filer is around the national median household income on their own, which puts a two-earner household at this level comfortably into the upper half. The salary is typical of experienced professionals, mid-career engineers, senior nurses and managers outside the largest cities. The marginal federal rate is 22 per cent and rises to 24 shortly above this point, so a pay rise from here is worth planning around: directing part of it into a 401(k) or HSA keeps the taxable income under the next threshold and preserves the phase-outs that start to bite. The other threshold worth watching here is the student loan interest deduction, which phases out through the eighties for a single filer and disappears entirely above it. Body of advice aside, the arithmetic is simple here: each pre-tax dollar is worth 22 cents saved.",
  90000:
    "A $90,000 salary is firmly in the upper third of American earners and, for a single filer, straddles the 22 and 24 per cent federal brackets. It is typical of senior technical staff, experienced managers and specialised professionals. At this level the arithmetic of tax planning starts to justify effort: maximising a 401(k) at $23,500 removes almost a quarter of the salary from taxable income and saves roughly $5,600 federally, before any state saving. It is also the level at which the gap between a state with no income tax and one with a high rate reaches several thousand dollars a year. A dual-income household at this level each should check the W-4 Step 2 box, because withholding calculated as though each salary were the only one is the commonest cause of a surprise bill in April.",
  100000:
    "Six figures remains a recognisable milestone, though what it buys varies more by location than any other salary on this list: $100,000 in a low-cost metro supports a comfortable family life, while the same figure in San Francisco or Manhattan is an ordinary professional income. Federally, a single filer's marginal rate is 24 per cent and the effective rate lands near 15 to 17 per cent after the standard deduction. At this level the full 401(k) allowance, an HSA and a backdoor Roth contribution together can move a meaningful share of income out of current taxation. It is worth separating the milestone from the arithmetic: crossing into six figures changes the marginal rate by two points, not the whole tax bill, and the effective rate moves by less than one.",
  120000:
    "At $120,000 a single filer is in the top fifth of American earners and squarely in the 24 per cent federal bracket, with the 32 per cent bracket visible above. The salary is typical of senior engineers, experienced managers, specialised consultants and physicians early in practice. Two thresholds start to matter here: the phase-out of the direct Roth IRA contribution for single filers, which pushes many earners towards the backdoor route, and the level at which state income tax becomes the largest single difference between one job offer and an equivalent one in another state. Anyone with equity compensation should also check the withholding on vesting, since the flat twenty-two per cent supplemental rate under-withholds at this income and the shortfall appears at filing. Checking the withholding once in the spring costs nothing and avoids a penalty in April.",
  150000:
    "A $150,000 salary places a single filer near the top tenth of American earners and into the 24 per cent federal bracket with the 32 per cent band beginning nearby. At this level the Social Security wage base starts to matter: earnings above $176,100 escape the 6.2 per cent tax, so the marginal payroll burden falls as income rises past that point. Roth IRA contributions are phased out entirely for a single filer, and the case for maximising every pre-tax vehicle — 401(k), HSA, deferred compensation where offered — is at its strongest. The other consequence is that charitable giving and mortgage interest start to make itemising worthwhile in some states, where the capped state and local deduction alone reaches the $10,000 limit. Reviewing the payroll figures once past the wage base is worth the ten minutes it takes.",
  200000:
    "At $200,000 a single filer crosses the threshold for the 0.9 per cent Additional Medicare Tax and, on investment income, the 3.8 per cent Net Investment Income Tax. The marginal federal rate is 32 per cent, rising to 35 shortly above, and in a state such as California or New York the combined marginal rate exceeds 40 per cent. The whole Social Security wage base has been paid by this point, so an extra dollar carries income tax and Medicare but no further Social Security. Planning at this level is about timing and vehicle choice rather than about deductions. A household at this level should also look at the timing of bonuses and of capital gains, since moving income across a tax year is often worth more than any deduction available at this point.",
};

/** Ce qui distingue cet État une fois l'impôt fédéral payé. */
export const PROSE_ETAT: Record<string, string> = {
  California:
    "California combines the highest state income tax in the country, running to 13.3 per cent at the top, with housing costs that dominate every household budget in the coastal metros. It also treats long-term capital gains as ordinary income, which no other state does at that rate. Against that, property tax is constrained by Proposition 13, which caps assessment growth at 2 per cent a year and leaves long-standing owners paying far less than recent buyers on identical houses. The practical consequence for a salaried worker is that the tax burden lands on income rather than on property, and it lands hard. For a salaried worker deciding between offers, the rule of thumb is that a California salary needs to be roughly ten per cent higher than a no-income-tax equivalent before housing is even considered.",
  Texas:
    "Texas levies no income tax on wages, and the prohibition sits in the state constitution rather than in ordinary law. The revenue comes from property tax instead, at an effective rate around 1.6 per cent of market value, among the highest in the country, and from a sales tax of 6.25 per cent that local additions push above 8 in most cities. For a renter the arithmetic is straightforwardly favourable; for a family buying a house, a substantial share of the income tax saving returns as a property tax bill that arrives whether or not the household earns anything that year. The practical rule for anyone moving here is to price the property tax on the house they intend to buy before treating the income tax saving as spendable.",
  Florida:
    "Florida has no state income tax, protected by the state constitution, and funds itself through a 6 per cent sales tax with local surtaxes, property taxes, and levies tied to tourism and real estate transactions. Property tax is moderated for permanent residents by the homestead exemption and the Save Our Homes cap, which limits assessment growth to 3 per cent a year. The offsetting cost that catches newcomers is insurance: homeowners' premiums in the coastal counties have risen to levels that can exceed the property tax itself, and they are not deductible. Anyone comparing an offer here with one in a taxed state should get an insurance quote for the specific address before counting the income tax saving. The homestead exemption has to be claimed, and a late filing waits a full year to take effect.",
  "New York":
    "New York taxes income progressively to 10.9 per cent, and residents of New York City pay a further municipal tax of 3.078 to 3.876 per cent on top, which no commuter pays. That city layer is the single largest financial difference between living in Brooklyn and living across the river in New Jersey. The state also applies the convenience-of-the-employer rule, taxing days worked remotely for a New York employer as though they had been worked in the state, which has caught a great many hybrid workers since 2020 and is worth checking before assuming a move lowers the bill. The practical rule is to compare take-home pay for the specific address rather than the salary, because the city line alone can swing the answer by several thousand dollars a year.",
  Pennsylvania:
    "Pennsylvania applies a flat state income tax of 3.07 per cent, one of the lowest flat rates in the country, and it does not tax retirement income at all, which makes it unusually attractive to pensioners. The complication is local: most municipalities levy an earned income tax, commonly 1 per cent split between the township and the school district, and Philadelphia charges a wage tax of 3.75 per cent on residents and 3.44 on non-residents who work in the city. On a Philadelphia salary that local line is larger than the state one. A worker choosing between a job in the city and one in a suburb should therefore compare take-home pay rather than salary, since the wage tax can swing the answer by thousands.",
  Illinois:
    "Illinois applies a flat income tax of 4.95 per cent, which a constitutional amendment attempt failed to replace with a progressive schedule in 2020. Retirement income is exempt, an unusually generous treatment. The weight of the burden falls on property: effective rates above 2 per cent of market value in much of Cook County are among the highest in the nation, driven by school district funding and pension obligations. For a salaried renter the state is moderately taxed; for a homeowner in the Chicago suburbs the total picture is very different. Comparing offers here means comparing the property tax bill of the actual house, because the flat income tax makes the state layer easy to predict and the local layer anything but. Two identical salaries can leave very different amounts in hand once the county bill arrives.",
  Ohio:
    "Ohio has moved towards a flatter income tax with modest rates and a substantial exemption for the lowest incomes, so the state line on a payslip is comparatively light. The local line is not: a great many Ohio municipalities levy their own income tax of 1 to 3 per cent, Columbus, Cleveland and Cincinnati included, and the tax generally follows where the work is performed rather than where the worker lives, with only a partial credit from the home municipality. A commute between two taxing cities can therefore cost more in local tax than the state charges. Before accepting a job in another municipality, it is worth asking which city tax applies and what credit your own city gives, because the answer changes the take-home figure directly.",
  Georgia:
    "Georgia has replaced its progressive schedule with a flat income tax and has been reducing the rate in steps, which makes it one of the lighter-taxed states in the Southeast on wages. Property tax is close to the national average, and the sales tax, 4 per cent at state level, rises to 7 or 8 with county additions. Retirement income receives a large exclusion from age 62, which is one reason the state attracts retirees from higher-tax jurisdictions. For a working household, the notable feature is how little the state layer varies with income. For a household weighing a move, the predictability is itself worth something: the state layer is easy to forecast, and the variable that matters is housing rather than tax. Checking the current rate before comparing offers matters, since it has moved almost every year.",
  "North Carolina":
    "North Carolina applies a flat income tax that has been cut repeatedly over the past decade and is scheduled to fall further, which has taken it from one of the higher-taxed states in the region to one of the lower. The standard deduction is generous relative to the rate, so the effective burden at modest salaries is lighter than the headline suggests. Property tax is below the national average, and the combined sales tax sits near 7 per cent. The state's appeal to relocating workers rests as much on that predictability as on the level. Anyone comparing an offer here with one in a neighbouring state should use the current-year rate rather than an older figure, because the schedule has changed repeatedly in recent years.",
  Michigan:
    "Michigan levies a flat income tax of around 4.25 per cent, and a number of cities — Detroit, Grand Rapids, Lansing among them — add a local income tax on top, typically 1 per cent for residents and half that for non-residents. Property tax is above the national average but moderated for owner-occupiers by the principal residence exemption, which removes the school operating levy. Retirement income is treated increasingly favourably following recent changes. For a salaried worker the state line is simple to predict, which is not true of the city line. Anyone taking a job in one of the taxing cities should check whether the local tax applies to residents only or to commuters too, since the two rates differ by half. Asking the employer which city withholding applies avoids an unwelcome reconciliation at filing.",
};
