/**
 * Prose propre au montant et à l'État, pour les pages /:state/:amount-after-taxes.
 *
 * Le contrôle d'unicité a trouvé 3 259 paires de pages proches à 100 % : les
 * cent vingt pages d'État partageaient le même texte, seuls les nombres
 * changeaient, et un contrôle qui normalise les nombres voit alors deux pages
 * identiques. Un moteur aussi.
 *
 * Plutôt que d'écrire cent vingt textes, on en écrit vingt-deux : un par
 * montant et un par État. Chaque page porte la paire qui lui correspond, et
 * aucune combinaison ne se répète. Les paragraphes disent quelque chose que la
 * page ne dit pas ailleurs : à quoi ressemble ce niveau de salaire dans la vie
 * réelle, et ce qui distingue cet État des autres une fois l'impôt payé.
 */

/** Ce que représente ce niveau de salaire, indépendamment de l'État. */
export const PROSE_MONTANT: Record<number, string> = {
  30000:
    "A salary of $30,000 sits close to the full-time federal minimum wage in real terms and well below the national median household income. It is typical of retail, food service, care work and entry-level administrative roles, and it usually assumes a second earner, a roommate or subsidised housing to work as a household budget. At this level the federal tax bill is modest: after the standard deduction, most of the income falls in the 10 and 12 per cent brackets, and FICA at 7.65 per cent takes more than income tax does. The Earned Income Tax Credit and the Saver's Credit both matter here and are routinely missed.",
  40000:
    "A $40,000 salary is common for skilled trades apprentices, teaching assistants, junior clerical staff and experienced retail supervisors. It is enough to run a one-person household in most of the country and tight in any coastal metro. Federal tax stays largely in the 12 per cent bracket after the standard deduction, so the marginal effect of a raise is mild, and FICA remains the larger deduction. This is the income band where a workplace retirement match is most often left on the table: contributing enough to capture it is the single highest-return decision available at this salary.",
  50000:
    "At $50,000, a worker is near the median for an individual American earner, though still below the median household, which counts two incomes in most cases. The salary covers teachers in many states, administrative professionals, technicians and skilled trades early in a career. Federally, part of the income now reaches the 22 per cent bracket, which makes pre-tax contributions worth measurably more than they were at $40,000: every dollar into a traditional 401(k) saves 22 cents rather than 12. It is also the level at which the choice between a high-tax and a no-income-tax state starts to show up in real money.",
  60000:
    "A $60,000 salary supports a comfortable single-person household almost anywhere outside the most expensive metros, and a modest family budget in low-cost regions. It is typical of experienced tradespeople, nurses early in a career, mid-level administrators and many engineering graduates in their first years. The marginal federal rate is 22 per cent for a single filer, so a $5,000 pre-tax contribution saves $1,100 federally before any state saving. At this level the difference between the states is roughly $2,000 to $3,000 a year between the lightest and the heaviest, which is real but rarely decisive on its own.",
  70000:
    "At $70,000 a single filer is comfortably above the median individual income and within reach of the financial habits that compound: a full emergency fund, a maxed IRA, a meaningful 401(k) contribution. The salary is typical of experienced nurses, software developers outside the major hubs, project managers and skilled specialists. The marginal federal rate remains 22 per cent, which means the top slice of income is taxed at more than twice the rate of the bottom slice, and it is the slice that pre-tax contributions remove first. Housing is usually still the constraint rather than tax.",
  75000:
    "A $75,000 salary is often quoted as the point at which additional income stops improving day-to-day wellbeing much, a finding from research that has since been qualified but still marks a recognisable threshold. In practice it supports a single-earner household in most of the country and a two-earner family comfortably. Federally, the marginal rate is 22 per cent and the effective rate lands near 12 to 14 per cent after the standard deduction. This is also the level at which the phase-outs begin to matter: several credits and deduction allowances start to taper in the seventies and eighties.",
  80000:
    "At $80,000, a single filer is around the national median household income on their own, which puts a two-earner household at this level comfortably into the upper half. The salary is typical of experienced professionals, mid-career engineers, senior nurses and managers outside the largest cities. The marginal federal rate is 22 per cent and rises to 24 shortly above this point, so a pay rise from here is worth planning around: directing part of it into a 401(k) or HSA keeps the taxable income under the next threshold and preserves the phase-outs that start to bite.",
  90000:
    "A $90,000 salary is firmly in the upper third of American earners and, for a single filer, straddles the 22 and 24 per cent federal brackets. It is typical of senior technical staff, experienced managers and specialised professionals. At this level the arithmetic of tax planning starts to justify effort: maximising a 401(k) at $23,500 removes almost a quarter of the salary from taxable income and saves roughly $5,600 federally, before any state saving. It is also the level at which the gap between a state with no income tax and one with a high rate reaches several thousand dollars a year.",
  100000:
    "Six figures remains a recognisable milestone, though what it buys varies more by location than any other salary on this list: $100,000 in a low-cost metro supports a comfortable family life, while the same figure in San Francisco or Manhattan is an ordinary professional income. Federally, a single filer's marginal rate is 24 per cent and the effective rate lands near 15 to 17 per cent after the standard deduction. At this level the full 401(k) allowance, an HSA and a backdoor Roth contribution together can move a meaningful share of income out of current taxation.",
  120000:
    "At $120,000 a single filer is in the top fifth of American earners and squarely in the 24 per cent federal bracket, with the 32 per cent bracket visible above. The salary is typical of senior engineers, experienced managers, specialised consultants and physicians early in practice. Two thresholds start to matter here: the phase-out of the direct Roth IRA contribution for single filers, which pushes many earners towards the backdoor route, and the level at which state income tax becomes the largest single difference between one job offer and an equivalent one in another state.",
  150000:
    "A $150,000 salary places a single filer near the top tenth of American earners and into the 24 per cent federal bracket with the 32 per cent band beginning nearby. At this level the Social Security wage base starts to matter: earnings above $176,100 escape the 6.2 per cent tax, so the marginal payroll burden falls as income rises past that point. Roth IRA contributions are phased out entirely for a single filer, and the case for maximising every pre-tax vehicle — 401(k), HSA, deferred compensation where offered — is at its strongest.",
  200000:
    "At $200,000 a single filer crosses the threshold for the 0.9 per cent Additional Medicare Tax and, on investment income, the 3.8 per cent Net Investment Income Tax. The marginal federal rate is 32 per cent, rising to 35 shortly above, and in a state such as California or New York the combined marginal rate exceeds 40 per cent. The whole Social Security wage base has been paid by this point, so an extra dollar carries income tax and Medicare but no further Social Security. Planning at this level is about timing and vehicle choice rather than about deductions.",
};

/** Ce qui distingue cet État une fois l'impôt fédéral payé. */
export const PROSE_ETAT: Record<string, string> = {
  California:
    "California combines the highest state income tax in the country, running to 13.3 per cent at the top, with housing costs that dominate every household budget in the coastal metros. It also treats long-term capital gains as ordinary income, which no other state does at that rate. Against that, property tax is constrained by Proposition 13, which caps assessment growth at 2 per cent a year and leaves long-standing owners paying far less than recent buyers on identical houses. The practical consequence for a salaried worker is that the tax burden lands on income rather than on property, and it lands hard.",
  Texas:
    "Texas levies no income tax on wages, and the prohibition sits in the state constitution rather than in ordinary law. The revenue comes from property tax instead, at an effective rate around 1.6 per cent of market value, among the highest in the country, and from a sales tax of 6.25 per cent that local additions push above 8 in most cities. For a renter the arithmetic is straightforwardly favourable; for a family buying a house, a substantial share of the income tax saving returns as a property tax bill that arrives whether or not the household earns anything that year.",
  Florida:
    "Florida has no state income tax, protected by the state constitution, and funds itself through a 6 per cent sales tax with local surtaxes, property taxes, and levies tied to tourism and real estate transactions. Property tax is moderated for permanent residents by the homestead exemption and the Save Our Homes cap, which limits assessment growth to 3 per cent a year. The offsetting cost that catches newcomers is insurance: homeowners' premiums in the coastal counties have risen to levels that can exceed the property tax itself, and they are not deductible.",
  "New York":
    "New York taxes income progressively to 10.9 per cent, and residents of New York City pay a further municipal tax of 3.078 to 3.876 per cent on top, which no commuter pays. That city layer is the single largest financial difference between living in Brooklyn and living across the river in New Jersey. The state also applies the convenience-of-the-employer rule, taxing days worked remotely for a New York employer as though they had been worked in the state, which has caught a great many hybrid workers since 2020 and is worth checking before assuming a move lowers the bill.",
  Pennsylvania:
    "Pennsylvania applies a flat state income tax of 3.07 per cent, one of the lowest flat rates in the country, and it does not tax retirement income at all, which makes it unusually attractive to pensioners. The complication is local: most municipalities levy an earned income tax, commonly 1 per cent split between the township and the school district, and Philadelphia charges a wage tax of 3.75 per cent on residents and 3.44 on non-residents who work in the city. On a Philadelphia salary that local line is larger than the state one.",
  Illinois:
    "Illinois applies a flat income tax of 4.95 per cent, which a constitutional amendment attempt failed to replace with a progressive schedule in 2020. Retirement income is exempt, an unusually generous treatment. The weight of the burden falls on property: effective rates above 2 per cent of market value in much of Cook County are among the highest in the nation, driven by school district funding and pension obligations. For a salaried renter the state is moderately taxed; for a homeowner in the Chicago suburbs the total picture is very different.",
  Ohio:
    "Ohio has moved towards a flatter income tax with modest rates and a substantial exemption for the lowest incomes, so the state line on a payslip is comparatively light. The local line is not: a great many Ohio municipalities levy their own income tax of 1 to 3 per cent, Columbus, Cleveland and Cincinnati included, and the tax generally follows where the work is performed rather than where the worker lives, with only a partial credit from the home municipality. A commute between two taxing cities can therefore cost more in local tax than the state charges.",
  Georgia:
    "Georgia has replaced its progressive schedule with a flat income tax and has been reducing the rate in steps, which makes it one of the lighter-taxed states in the Southeast on wages. Property tax is close to the national average, and the sales tax, 4 per cent at state level, rises to 7 or 8 with county additions. Retirement income receives a large exclusion from age 62, which is one reason the state attracts retirees from higher-tax jurisdictions. For a working household, the notable feature is how little the state layer varies with income.",
  "North Carolina":
    "North Carolina applies a flat income tax that has been cut repeatedly over the past decade and is scheduled to fall further, which has taken it from one of the higher-taxed states in the region to one of the lower. The standard deduction is generous relative to the rate, so the effective burden at modest salaries is lighter than the headline suggests. Property tax is below the national average, and the combined sales tax sits near 7 per cent. The state's appeal to relocating workers rests as much on that predictability as on the level.",
  Michigan:
    "Michigan levies a flat income tax of around 4.25 per cent, and a number of cities — Detroit, Grand Rapids, Lansing among them — add a local income tax on top, typically 1 per cent for residents and half that for non-residents. Property tax is above the national average but moderated for owner-occupiers by the principal residence exemption, which removes the school operating levy. Retirement income is treated increasingly favourably following recent changes. For a salaried worker the state line is simple to predict, which is not true of the city line.",
};
